version: '2'

services:
  db:
    image: mariadb
    container_name: db
    volumes:
      - ./data:/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3000:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=MARTA
